### ISSUE TITLE
Infer only the road segmentation

### ISSUE THREAD

**Issue by zillur01** [ibaiGorordo/ONNX-HybridNets-Multitask-Road-Detection#2]
Thanks for this excellent work. How do I get only the road segmentation result? I do not need the object detection. Hope it will reduce inference time too.

**Comment by ibaiGorordo** [comment]
Do you mean to only draw the segmentation, or remove the detection part from the model?

In the first case, you can use `draw_segmentation` function instead of using the draw_2d function as in the example.

In the other case it is probably possible using some of the ONNX tools (https://github.com/PINTO0309/simple-onnx-processing-tools), but it is probably easier to do in Pytorch and convert the model to ONNX again.
